export const seedEnemies = [
  {
    name: "Rata de Alcantarilla",
    level: 1,
    stats: {
      strength: 3,
      dexterity: 4,
      intelligence: 1,
      vitality: 3,
      physicalDefense: 2,
      magicalDefense: 1,
      luck: 1,
      agility: 4,
      endurance: 2,
      wisdom: 1,
    },
    resistances: {
      fire: 0,
      ice: 1,
      lightning: 0,
      poison: 2,
      sleep: 1,
      paralysis: 1,
      confusion: 0,
      fear: 1,
      dark: 1,
      holy: 0,
      stun: 1,
      bleed: 1,
      curse: 0,
      knockback: 1,
      criticalChanceReduction: 0,
      criticalDamageReduction: 0,
    },
    combatStats: {
      maxHP: 45,
      maxMP: 10,
      attackPower: 8,
      magicPower: 2,
      criticalChance: 4,
      criticalDamageBonus: 20,
      attackSpeed: 6,
      evasion: 6,
      blockChance: 0,
      blockValue: 0,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 0,
      movementSpeed: 5,
    },
    imageUrl: "/assets/enemies/sewer_rat.png",
  },
  {
    name: "Murciélago de Cripta",
    level: 2,
    stats: {
      strength: 3,
      dexterity: 5,
      intelligence: 2,
      vitality: 4,
      physicalDefense: 2,
      magicalDefense: 2,
      luck: 2,
      agility: 6,
      endurance: 3,
      wisdom: 1,
    },
    resistances: {
      fire: 0,
      ice: 2,
      lightning: 1,
      poison: 1,
      sleep: 1,
      paralysis: 1,
      confusion: 1,
      fear: 2,
      dark: 2,
      holy: 0,
      stun: 2,
      bleed: 1,
      curse: 0,
      knockback: 1,
      criticalChanceReduction: 1,
      criticalDamageReduction: 0,
    },
    combatStats: {
      maxHP: 60,
      maxMP: 15,
      attackPower: 10,
      magicPower: 3,
      criticalChance: 6,
      criticalDamageBonus: 22,
      attackSpeed: 7,
      evasion: 8,
      blockChance: 0,
      blockValue: 0,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 1,
      movementSpeed: 6,
    },
    imageUrl: "/assets/enemies/crypt_bat.png",
  },
  {
    name: "Esqueleto Débil",
    level: 3,
    stats: {
      strength: 5,
      dexterity: 4,
      intelligence: 2,
      vitality: 5,
      physicalDefense: 3,
      magicalDefense: 2,
      luck: 2,
      agility: 4,
      endurance: 3,
      wisdom: 1,
    },
    resistances: {
      fire: 1,
      ice: 1,
      lightning: 1,
      poison: 3,
      sleep: 0,
      paralysis: 1,
      confusion: 1,
      fear: 2,
      dark: 3,
      holy: 0,
      stun: 2,
      bleed: 0,
      curse: 2,
      knockback: 2,
      criticalChanceReduction: 1,
      criticalDamageReduction: 1,
    },
    combatStats: {
      maxHP: 70,
      maxMP: 15,
      attackPower: 12,
      magicPower: 3,
      criticalChance: 5,
      criticalDamageBonus: 22,
      attackSpeed: 5,
      evasion: 4,
      blockChance: 2,
      blockValue: 3,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 1,
      movementSpeed: 4,
    },
    imageUrl: "/assets/enemies/weak_skeleton.png",
  },
  {
    name: "Bandido Novato",
    level: 4,
    stats: {
      strength: 6,
      dexterity: 6,
      intelligence: 2,
      vitality: 5,
      physicalDefense: 3,
      magicalDefense: 2,
      luck: 3,
      agility: 6,
      endurance: 4,
      wisdom: 2,
    },
    resistances: {
      fire: 1,
      ice: 1,
      lightning: 1,
      poison: 2,
      sleep: 1,
      paralysis: 1,
      confusion: 1,
      fear: 1,
      dark: 1,
      holy: 1,
      stun: 2,
      bleed: 2,
      curse: 1,
      knockback: 2,
      criticalChanceReduction: 1,
      criticalDamageReduction: 1,
    },
    combatStats: {
      maxHP: 85,
      maxMP: 20,
      attackPower: 16,
      magicPower: 4,
      criticalChance: 7,
      criticalDamageBonus: 24,
      attackSpeed: 6,
      evasion: 6,
      blockChance: 2,
      blockValue: 3,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 2,
      movementSpeed: 5,
    },
    imageUrl: "/assets/enemies/rookie_bandit.png",
  },
  {
    name: "Bruto de Aldea",
    level: 5,
    stats: {
      strength: 8,
      dexterity: 5,
      intelligence: 1,
      vitality: 8,
      physicalDefense: 5,
      magicalDefense: 2,
      luck: 2,
      agility: 4,
      endurance: 6,
      wisdom: 1,
    },
    resistances: {
      fire: 2,
      ice: 2,
      lightning: 1,
      poison: 2,
      sleep: 1,
      paralysis: 2,
      confusion: 1,
      fear: 2,
      dark: 1,
      holy: 1,
      stun: 3,
      bleed: 3,
      curse: 1,
      knockback: 3,
      criticalChanceReduction: 2,
      criticalDamageReduction: 2,
    },
    combatStats: {
      maxHP: 120,
      maxMP: 15,
      attackPower: 19,
      magicPower: 3,
      criticalChance: 5,
      criticalDamageBonus: 25,
      attackSpeed: 5,
      evasion: 4,
      blockChance: 4,
      blockValue: 5,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 3,
      movementSpeed: 4,
    },
    imageUrl: "/assets/enemies/village_brute.png",
  },
  {
    name: "Bandido Rufián",
    level: 5,
    stats: {
      strength: 7,
      dexterity: 7,
      intelligence: 3,
      vitality: 7,
      physicalDefense: 5,
      magicalDefense: 3,
      luck: 3,
      agility: 6,
      endurance: 5,
      wisdom: 2,
    },
    resistances: {
      fire: 2,
      ice: 2,
      lightning: 2,
      poison: 3,
      sleep: 2,
      paralysis: 2,
      confusion: 2,
      fear: 2,
      dark: 2,
      holy: 2,
      stun: 3,
      bleed: 3,
      curse: 2,
      knockback: 2,
      criticalChanceReduction: 2,
      criticalDamageReduction: 2,
    },
    combatStats: {
      maxHP: 95,
      maxMP: 30,
      attackPower: 18,
      magicPower: 5,
      criticalChance: 8,
      criticalDamageBonus: 25,
      attackSpeed: 6,
      evasion: 6,
      blockChance: 3,
      blockValue: 4,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 3,
      movementSpeed: 5,
    },
    imageUrl: "/assets/enemies/bandit.png",
  },
  {
    name: "Arquero Carroñero",
    level: 5,
    stats: {
      strength: 6,
      dexterity: 8,
      intelligence: 3,
      vitality: 6,
      physicalDefense: 3,
      magicalDefense: 3,
      luck: 3,
      agility: 8,
      endurance: 4,
      wisdom: 2,
    },
    resistances: {
      fire: 1,
      ice: 2,
      lightning: 2,
      poison: 2,
      sleep: 2,
      paralysis: 2,
      confusion: 2,
      fear: 2,
      dark: 2,
      holy: 1,
      stun: 2,
      bleed: 2,
      curse: 1,
      knockback: 2,
      criticalChanceReduction: 2,
      criticalDamageReduction: 1,
    },
    combatStats: {
      maxHP: 90,
      maxMP: 25,
      attackPower: 17,
      magicPower: 4,
      criticalChance: 10,
      criticalDamageBonus: 28,
      attackSpeed: 7,
      evasion: 8,
      blockChance: 1,
      blockValue: 2,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 2,
      movementSpeed: 6,
    },
    imageUrl: "/assets/enemies/scavenger_archer.png",
  },
  {
    name: "Lobo Hambriento",
    level: 6,
    stats: {
      strength: 8,
      dexterity: 9,
      intelligence: 2,
      vitality: 7,
      physicalDefense: 4,
      magicalDefense: 2,
      luck: 3,
      agility: 9,
      endurance: 5,
      wisdom: 2,
    },
    resistances: {
      fire: 1,
      ice: 3,
      lightning: 2,
      poison: 3,
      sleep: 2,
      paralysis: 3,
      confusion: 1,
      fear: 4,
      dark: 2,
      holy: 2,
      stun: 4,
      bleed: 2,
      curse: 1,
      knockback: 3,
      criticalChanceReduction: 2,
      criticalDamageReduction: 2,
    },
    combatStats: {
      maxHP: 105,
      maxMP: 20,
      attackPower: 20,
      magicPower: 4,
      criticalChance: 12,
      criticalDamageBonus: 30,
      attackSpeed: 8,
      evasion: 10,
      blockChance: 0,
      blockValue: 0,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 2,
      movementSpeed: 7,
    },
    imageUrl: "/assets/enemies/wolf.png",
  },
  {
    name: "Cultista Umbrío",
    level: 7,
    stats: {
      strength: 4,
      dexterity: 6,
      intelligence: 9,
      vitality: 6,
      physicalDefense: 3,
      magicalDefense: 7,
      luck: 4,
      agility: 5,
      endurance: 5,
      wisdom: 8,
    },
    resistances: {
      fire: 3,
      ice: 4,
      lightning: 4,
      poison: 2,
      sleep: 3,
      paralysis: 2,
      confusion: 5,
      fear: 5,
      dark: 6,
      holy: 1,
      stun: 3,
      bleed: 2,
      curse: 6,
      knockback: 2,
      criticalChanceReduction: 3,
      criticalDamageReduction: 2,
    },
    combatStats: {
      maxHP: 90,
      maxMP: 100,
      attackPower: 10,
      magicPower: 24,
      criticalChance: 10,
      criticalDamageBonus: 30,
      attackSpeed: 5,
      evasion: 6,
      blockChance: 2,
      blockValue: 3,
      lifeSteal: 0,
      manaSteal: 2,
      damageReduction: 4,
      movementSpeed: 4,
    },
    imageUrl: "/assets/enemies/cultist.png",
  },
  {
    name: "Gólem de Arcilla",
    level: 8,
    stats: {
      strength: 12,
      dexterity: 3,
      intelligence: 2,
      vitality: 12,
      physicalDefense: 9,
      magicalDefense: 4,
      luck: 2,
      agility: 2,
      endurance: 10,
      wisdom: 2,
    },
    resistances: {
      fire: 2,
      ice: 4,
      lightning: 1,
      poison: 5,
      sleep: 0,
      paralysis: 3,
      confusion: 0,
      fear: 5,
      dark: 3,
      holy: 2,
      stun: 5,
      bleed: 0,
      curse: 3,
      knockback: 5,
      criticalChanceReduction: 4,
      criticalDamageReduction: 4,
    },
    combatStats: {
      maxHP: 220,
      maxMP: 20,
      attackPower: 26,
      magicPower: 6,
      criticalChance: 4,
      criticalDamageBonus: 25,
      attackSpeed: 3,
      evasion: 2,
      blockChance: 6,
      blockValue: 10,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 8,
      movementSpeed: 3,
    },
    imageUrl: "/assets/enemies/clay_golem.png",
  },
  {
    name: "Chamán Tribal",
    level: 9,
    stats: {
      strength: 6,
      dexterity: 6,
      intelligence: 12,
      vitality: 8,
      physicalDefense: 4,
      magicalDefense: 8,
      luck: 4,
      agility: 5,
      endurance: 6,
      wisdom: 10,
    },
    resistances: {
      fire: 5,
      ice: 5,
      lightning: 5,
      poison: 3,
      sleep: 3,
      paralysis: 3,
      confusion: 4,
      fear: 4,
      dark: 5,
      holy: 3,
      stun: 3,
      bleed: 2,
      curse: 6,
      knockback: 3,
      criticalChanceReduction: 3,
      criticalDamageReduction: 3,
    },
    combatStats: {
      maxHP: 140,
      maxMP: 140,
      attackPower: 14,
      magicPower: 30,
      criticalChance: 10,
      criticalDamageBonus: 32,
      attackSpeed: 5,
      evasion: 5,
      blockChance: 2,
      blockValue: 3,
      lifeSteal: 0,
      manaSteal: 3,
      damageReduction: 4,
      movementSpeed: 4,
    },
    imageUrl: "/assets/enemies/tribal_shaman.png",
  },
  {
    name: "Caballero Deshonrado",
    level: 10,
    stats: {
      strength: 14,
      dexterity: 7,
      intelligence: 4,
      vitality: 12,
      physicalDefense: 10,
      magicalDefense: 6,
      luck: 4,
      agility: 5,
      endurance: 10,
      wisdom: 4,
    },
    resistances: {
      fire: 4,
      ice: 4,
      lightning: 3,
      poison: 4,
      sleep: 2,
      paralysis: 3,
      confusion: 2,
      fear: 4,
      dark: 4,
      holy: 2,
      stun: 5,
      bleed: 4,
      curse: 3,
      knockback: 5,
      criticalChanceReduction: 4,
      criticalDamageReduction: 4,
    },
    combatStats: {
      maxHP: 260,
      maxMP: 40,
      attackPower: 32,
      magicPower: 8,
      criticalChance: 8,
      criticalDamageBonus: 30,
      attackSpeed: 5,
      evasion: 4,
      blockChance: 10,
      blockValue: 14,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 9,
      movementSpeed: 4,
    },
    imageUrl: "/assets/enemies/dishonored_knight.png",
  },
  {
    name: "Bruja del Brezal",
    level: 11,
    stats: {
      strength: 5,
      dexterity: 7,
      intelligence: 15,
      vitality: 9,
      physicalDefense: 4,
      magicalDefense: 10,
      luck: 5,
      agility: 6,
      endurance: 6,
      wisdom: 12,
    },
    resistances: {
      fire: 6,
      ice: 7,
      lightning: 7,
      poison: 4,
      sleep: 5,
      paralysis: 4,
      confusion: 6,
      fear: 6,
      dark: 7,
      holy: 3,
      stun: 3,
      bleed: 2,
      curse: 8,
      knockback: 3,
      criticalChanceReduction: 3,
      criticalDamageReduction: 3,
    },
    combatStats: {
      maxHP: 160,
      maxMP: 180,
      attackPower: 16,
      magicPower: 38,
      criticalChance: 12,
      criticalDamageBonus: 35,
      attackSpeed: 6,
      evasion: 6,
      blockChance: 2,
      blockValue: 3,
      lifeSteal: 0,
      manaSteal: 4,
      damageReduction: 5,
      movementSpeed: 5,
    },
    imageUrl: "/assets/enemies/heath_witch.png",
  },
  {
    name: "Saurio Blindado",
    level: 12,
    stats: {
      strength: 18,
      dexterity: 8,
      intelligence: 4,
      vitality: 16,
      physicalDefense: 12,
      magicalDefense: 6,
      luck: 4,
      agility: 5,
      endurance: 12,
      wisdom: 4,
    },
    resistances: {
      fire: 5,
      ice: 6,
      lightning: 4,
      poison: 5,
      sleep: 2,
      paralysis: 4,
      confusion: 2,
      fear: 5,
      dark: 4,
      holy: 3,
      stun: 6,
      bleed: 5,
      curse: 3,
      knockback: 6,
      criticalChanceReduction: 5,
      criticalDamageReduction: 5,
    },
    combatStats: {
      maxHP: 340,
      maxMP: 40,
      attackPower: 38,
      magicPower: 8,
      criticalChance: 8,
      criticalDamageBonus: 32,
      attackSpeed: 4,
      evasion: 3,
      blockChance: 8,
      blockValue: 16,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 11,
      movementSpeed: 4,
    },
    imageUrl: "/assets/enemies/armored_saurian.png",
  },
  {
    name: "Señor de los Bandidos",
    level: 13,
    stats: {
      strength: 16,
      dexterity: 14,
      intelligence: 6,
      vitality: 14,
      physicalDefense: 9,
      magicalDefense: 6,
      luck: 7,
      agility: 12,
      endurance: 10,
      wisdom: 5,
    },
    resistances: {
      fire: 5,
      ice: 5,
      lightning: 5,
      poison: 5,
      sleep: 3,
      paralysis: 3,
      confusion: 3,
      fear: 5,
      dark: 4,
      holy: 3,
      stun: 5,
      bleed: 4,
      curse: 4,
      knockback: 5,
      criticalChanceReduction: 4,
      criticalDamageReduction: 4,
    },
    combatStats: {
      maxHP: 300,
      maxMP: 60,
      attackPower: 36,
      magicPower: 10,
      criticalChance: 16,
      criticalDamageBonus: 40,
      attackSpeed: 7,
      evasion: 10,
      blockChance: 4,
      blockValue: 6,
      lifeSteal: 2,
      manaSteal: 0,
      damageReduction: 7,
      movementSpeed: 6,
    },
    imageUrl: "/assets/enemies/bandit_lord.png",
  },
  {
    name: "Caballero de Ébano",
    level: 14,
    stats: {
      strength: 20,
      dexterity: 10,
      intelligence: 6,
      vitality: 18,
      physicalDefense: 14,
      magicalDefense: 8,
      luck: 6,
      agility: 6,
      endurance: 14,
      wisdom: 6,
    },
    resistances: {
      fire: 6,
      ice: 6,
      lightning: 5,
      poison: 6,
      sleep: 3,
      paralysis: 4,
      confusion: 3,
      fear: 6,
      dark: 7,
      holy: 4,
      stun: 6,
      bleed: 5,
      curse: 5,
      knockback: 6,
      criticalChanceReduction: 5,
      criticalDamageReduction: 6,
    },
    combatStats: {
      maxHP: 400,
      maxMP: 60,
      attackPower: 44,
      magicPower: 12,
      criticalChance: 10,
      criticalDamageBonus: 38,
      attackSpeed: 5,
      evasion: 4,
      blockChance: 12,
      blockValue: 18,
      lifeSteal: 0,
      manaSteal: 0,
      damageReduction: 12,
      movementSpeed: 4,
    },
    imageUrl: "/assets/enemies/ebon_knight.png",
  },
  {
    name: "Quimera Menor",
    level: 15,
    stats: {
      strength: 22,
      dexterity: 12,
      intelligence: 10,
      vitality: 20,
      physicalDefense: 12,
      magicalDefense: 12,
      luck: 6,
      agility: 8,
      endurance: 16,
      wisdom: 8,
    },
    resistances: {
      fire: 8,
      ice: 7,
      lightning: 7,
      poison: 6,
      sleep: 4,
      paralysis: 5,
      confusion: 5,
      fear: 7,
      dark: 6,
      holy: 5,
      stun: 6,
      bleed: 5,
      curse: 6,
      knockback: 7,
      criticalChanceReduction: 6,
      criticalDamageReduction: 6,
    },
    combatStats: {
      maxHP: 480,
      maxMP: 120,
      attackPower: 50,
      magicPower: 28,
      criticalChance: 14,
      criticalDamageBonus: 42,
      attackSpeed: 6,
      evasion: 6,
      blockChance: 6,
      blockValue: 10,
      lifeSteal: 2,
      manaSteal: 2,
      damageReduction: 10,
      movementSpeed: 5,
    },
    imageUrl: "/assets/enemies/lesser_chimera.png",
  },
];
