export const seedCharacterClasses = [
  {
    name: "Guerrero",
    description: "Un guerrero cuya ira resuena como acero en la niebla. Guardián del reino caído.",
    iconName: "Shield",
    imageMainClassUrl: "/assets/classes/guerrero/guerrero_class_1.png",
    // ⇩ coincide con el motor: +5% DR y +3% Block
    passiveDefault: {
      name: "Espíritu de Guardia",
      description: "+5% reducción de daño y +3% probabilidad de bloqueo de forma constante.",
    },
    baseStats: {
      strength: 12,
      dexterity: 5,
      intelligence: 2,
      vitality: 10,
      physicalDefense: 9,
      magicalDefense: 3,
      luck: 2,
      endurance: 8,
    },
    resistances: {
      fire: 4,
      ice: 4,
      lightning: 2,
      poison: 3,
      sleep: 5,
      paralysis: 6,
      confusion: 4,
      fear: 5,
      dark: 2,
      holy: 4,
      stun: 7,
      bleed: 5,
      curse: 4,
      knockback: 6,
      criticalChanceReduction: 6,
      criticalDamageReduction: 5,
    },
    combatStats: {
      maxHP: 150,
      attackPower: 25,
      magicPower: 5,
      criticalChance: 5,
      criticalDamageBonus: 25,
      attackSpeed: 5,
      evasion: 5,
      blockChance: 15,
      blockValue: 20,
      lifeSteal: 2,
      damageReduction: 10,
      movementSpeed: 4,
    },
    subclasses: [
      {
        name: "Paladín Caído (Escudo)",
        slug: "paladin-caido-escudo",
        iconName: "Shield",
        imageSubclassUrl: "",
        passives: [
          { name: "Defensa Absoluta", description: "+15% defensa física bajo 30% de vida." },
          { name: "Resistencia Inquebrantable", description: "-15% daño crítico recibido." },
        ],
      },
      {
        name: "Verdugo de Hierro (Espada Dos Manos)",
        slug: "verdugo-hierro-espada-dos-manos",
        iconName: "Sword",
        imageSubclassUrl: "",
        passives: [
          { name: "Ira Desatada", description: "+15% daño físico con espadas de dos manos." },
          { name: "Carga Brutal", description: "Primer golpe tras moverse inflige +15% de daño." },
        ],
      },
    ],
  },

  {
    name: "Mago",
    description: "Un sabio anciano que canaliza el fuego ancestral y la escarcha del abismo.",
    iconName: "Flame",
    imageMainClassUrl: "/assets/classes/mago/mago_class_1.png",
    // ⇩ coincide con el motor: +30% MP → daño base + ramping +2%/ataque (máx +10%)
    passiveDefault: {
      name: "Llama Interna",
      description: "Convierte el 30% del Poder Mágico en daño base y aumenta el daño +2% por ataque (máx +10%).",
    },
    baseStats: {
      strength: 2,
      dexterity: 4,
      intelligence: 12,
      vitality: 6,
      physicalDefense: 3,
      magicalDefense: 9,
      luck: 3,
      endurance: 5,
    },
    resistances: {
      fire: 6,
      ice: 6,
      lightning: 5,
      poison: 2,
      sleep: 4,
      paralysis: 3,
      confusion: 5,
      fear: 4,
      dark: 6,
      holy: 4,
      stun: 3,
      bleed: 2,
      curse: 7,
      knockback: 3,
      criticalChanceReduction: 2,
      criticalDamageReduction: 2,
    },
    combatStats: {
      maxHP: 80,
      attackPower: 5,
      magicPower: 30,
      criticalChance: 8,
      criticalDamageBonus: 30,
      attackSpeed: 4,
      evasion: 6,
      blockChance: 2,
      blockValue: 5,
      lifeSteal: 0,
      damageReduction: 3,
      movementSpeed: 4,
    },
    subclasses: [
      {
        name: "Hechicero de Fuego",
        slug: "hechicero-fuego",
        iconName: "Flame",
        imageSubclassUrl: "",
        passives: [
          { name: "Ignición", description: "Explosión al acumular quemaduras." },
          { name: "Chispa Divina", description: "Chance de llamarada extra." },
        ],
      },
      {
        name: "Sabio del Hielo",
        slug: "sabio-hielo",
        iconName: "Snowflake",
        imageSubclassUrl: "",
        passives: [
          { name: "Aliento Glacial", description: "Chance de congelar enemigos." },
          { name: "Reacción Glacial", description: "Escudo de hielo tras recibir crítico." },
        ],
      },
    ],
  },

  {
    name: "Asesino",
    description: "Sombra sigilosa entre ruinas olvidadas. Su hoja envenenada susurra muerte.",
    iconName: "Ghost",
    imageMainClassUrl: "/assets/classes/asesino/asesino_class_1.png",
    // ⇩ coincide con el motor: +30% al bono de crítico (no a la chance)
    passiveDefault: {
      name: "Sombra Letal",
      description: "+30% al bono de daño crítico.",
    },
    baseStats: {
      strength: 6,
      dexterity: 10,
      intelligence: 4,
      vitality: 6,
      physicalDefense: 4,
      magicalDefense: 4,
      luck: 8,
      endurance: 5,
    },
    resistances: {
      fire: 3,
      ice: 4,
      lightning: 4,
      poison: 6,
      sleep: 4,
      paralysis: 4,
      confusion: 3,
      fear: 3,
      dark: 5,
      holy: 3,
      stun: 5,
      bleed: 5,
      curse: 3,
      knockback: 4,
      criticalChanceReduction: 4,
      criticalDamageReduction: 3,
    },
    combatStats: {
      maxHP: 100,
      attackPower: 20,
      magicPower: 10,
      criticalChance: 15,
      criticalDamageBonus: 40,
      attackSpeed: 8,
      evasion: 12,
      blockChance: 5,
      blockValue: 5,
      lifeSteal: 4,
      damageReduction: 5,
      movementSpeed: 6,
    },
    subclasses: [
      {
        name: "Acechador Nocturno",
        slug: "acechador-nocturno",
        iconName: "Ghost",
        imageSubclassUrl: "",
        passives: [
          { name: "Veneno Letal", description: "Aplica veneno con daño con el tiempo." },
          { name: "Toxina Paralizante", description: "Enemigos envenenados pueden quedar inmóviles brevemente." },
        ],
      },
      {
        name: "Danzarín de Sombras",
        slug: "danzarin-sombras",
        iconName: "Zap",
        imageSubclassUrl: "",
        passives: [
          { name: "Reflejo Fantasmal", description: "Probabilidad de evadir ataques." },
          { name: "Contraataque Sombrío", description: "Tras evadir, el siguiente ataque es crítico." },
        ],
      },
    ],
  },

  {
    name: "Arquero",
    description: "Cazador de la penumbra. Su arco canta desde los árboles muertos.",
    iconName: "GiBowArrow",
    imageMainClassUrl: "/assets/classes/arquero/arquero_class_1.png",
    // ⇩ coincide con el motor: ramping +1.5%/ataque (máx +7.5%)
    passiveDefault: {
      name: "Ojo del Águila",
      description: "Aumenta el daño +1.5% por ataque consecutivo (máx +7.5%).",
    },
    baseStats: {
      strength: 7,
      dexterity: 9,
      intelligence: 4,
      vitality: 6,
      physicalDefense: 5,
      magicalDefense: 4,
      luck: 6,
      endurance: 6,
    },
    resistances: {
      fire: 4,
      ice: 3,
      lightning: 5,
      poison: 4,
      sleep: 3,
      paralysis: 3,
      confusion: 4,
      fear: 4,
      dark: 4,
      holy: 3,
      stun: 4,
      bleed: 4,
      curse: 3,
      knockback: 3,
      criticalChanceReduction: 3,
      criticalDamageReduction: 3,
    },
    combatStats: {
      maxHP: 110,
      attackPower: 22,
      magicPower: 5,
      criticalChance: 12,
      criticalDamageBonus: 35,
      attackSpeed: 6,
      evasion: 8,
      blockChance: 3,
      blockValue: 4,
      lifeSteal: 3,
      damageReduction: 4,
      movementSpeed: 6,
    },
    subclasses: [
      {
        name: "Tirador de Precisión",
        slug: "tirador-precision",
        iconName: "Target",
        imageSubclassUrl: "",
        passives: [
          { name: "Pulso Preciso", description: "Disparo cargado inflige crítico garantizado." },
          { name: "Reflejo Ágil", description: "+velocidad de ataque tras esquivar." },
        ],
      },
      {
        name: "Sanguinario del Linde",
        slug: "sanguinario-linde",
        iconName: "FaSpider",
        imageSubclassUrl: "",
        passives: [
          { name: "Olor a sangre", description: "+daño a enemigos con <50% vida." },
          { name: "Tiro Venenoso", description: "Flecha inflige veneno con el tiempo." },
        ],
      },
    ],
  },
];
